# coding=utf-8
import sqlite3

with sqlite3.connect("sample.db") as connection:
    c = connection.cursor()
    c.execute('DROP TABLE places')
    #c.execute('DROP TABLE visits(visit_id INTEGER, place_id INTEGER, visit_date TEXT)')
    c.execute('CREATE TABLE places(place_id INTEGER, place_name TEXT, place_type TEXT, place_country TEXT, place_region TEXT)')
    #c.execute('CREATE TABLE visits(visit_id INTEGER, place_id INTEGER, visit_date TEXT)')
    #c.execute('INSERT INTO visits VALUES(1001,1,"апрель 2016")')
    #c.execute('INSERT INTO visits VALUES(1002,2,"сентябрь 2016")')
    c.execute('INSERT INTO places VALUES(1,"Москва","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(2,"Санкт-Петербург","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(3,"Псков","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(4,"Калуга","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(5,"Симферополь","city","Россия","Крым")')
    c.execute('INSERT INTO places VALUES(6,"Звенигород","city","Россия","Московская область")')
    c.execute('INSERT INTO places VALUES(7,"Акаба","city","Иордания",NULL)')
    c.execute('INSERT INTO places VALUES(8,"Вади Рам","desert","Иордания",NULL)')
    c.execute('INSERT INTO places VALUES(9,"Река Иордан","river","Иордания",NULL)')
    c.execute('INSERT INTO places VALUES(10,"Петра","city","Иордания",NULL)')
    c.execute('INSERT INTO places VALUES(11,"Тиват","city","Черногория",NULL)')
    c.execute('INSERT INTO places VALUES(12,"Котор","city","Черногория",NULL)')
    c.execute('INSERT INTO places VALUES(13,"Пераст","city","Черногория",NULL)')
    c.execute('INSERT INTO places VALUES(14,"Каменари","city","Черногория",NULL)')
    c.execute('INSERT INTO places VALUES(15,"Будва","city","Черногория",NULL)')
    c.execute('INSERT INTO places VALUES(16,"Бечичи","city","Черногория",NULL)')
    c.execute('INSERT INTO places VALUES(17,"Свети Стефан","city","Черногория",NULL)')
    c.execute('INSERT INTO places VALUES(18,"Ведикович","city","Черногория",NULL)')
    c.execute('INSERT INTO places VALUES(19,"Сергиев Посад","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(20,"Переславль-Залесский","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(21,"Борисоглебское","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(22,"Углич","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(23,"Калязин","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(24,"Киржач","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(25,"Торжок","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(26,"Осташков","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(27,"Старая Русса","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(28,"Великий Новгорд","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(29,"Печоры","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(30,"Изборск","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(31,"Великие Луки","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(32,"Волгоград","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(33,"Ереван","city","Армения",NULL)')
    c.execute('INSERT INTO places VALUES(34,"Вагаршапат","city","Армения",NULL)')
    c.execute('INSERT INTO places VALUES(35,"Сагмосаванк","city","Армения",NULL)')
    c.execute('INSERT INTO places VALUES(36,"Ховханнаванк","city","Армения",NULL)')
    c.execute('INSERT INTO places VALUES(37,"Татев","city","Армения",NULL)')
    c.execute('INSERT INTO places VALUES(38,"Чёртов мост, Татев","place","Армения",NULL)')
    c.execute('INSERT INTO places VALUES(39,"Хор Вирап","city","Армения",NULL)')
    c.execute('INSERT INTO places VALUES(40,"Нораванк","city","Армения",NULL)')
    c.execute('INSERT INTO places VALUES(41,"Сисиан","city","Армения",NULL)')
    c.execute('INSERT INTO places VALUES(42,"Галидзор","city","Армения",NULL)')
    c.execute('INSERT INTO places VALUES(43,"Гошаванк","city","Армения",NULL)')
    c.execute('INSERT INTO places VALUES(44,"Агарцин","city","Армения",NULL)')
    c.execute('INSERT INTO places VALUES(45,"Севан","lake","Армения",NULL)')
    c.execute('INSERT INTO places VALUES(46,"Гарни","city","Армения",NULL)')
    c.execute('INSERT INTO places VALUES(47,"Гегард","city","Армения",NULL)')
    c.execute('INSERT INTO places VALUES(48,"Великое","town","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(49,"Ярославль","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(50,"Талашкино","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(51,"Смоленск","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(52,"Вязьма","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(53,"Нижний Новгород","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(54,"Тула","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(55,"Рязань","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(56,"Константиново","town","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(57,"Зарайск","town","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(58,"Бахчисарай","city","Россия","Крым")')
    c.execute('INSERT INTO places VALUES(59,"Балаклава","city","Россия","Крым")')
    c.execute('INSERT INTO places VALUES(60,"Севастополь","city","Россия","Крым")')
    c.execute('INSERT INTO places VALUES(61,"Кострома","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(62,"Казань","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(63,"Чебоксары","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(64,"Йошкар-Ола","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(65,"Суздаль","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(66,"Владимир","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(67,"Нюрнберг","city","Германия",NULL)')
    c.execute('INSERT INTO places VALUES(68,"Штутгарт","city","Германия",NULL)')
    c.execute('INSERT INTO places VALUES(69,"Кобленц","city","Германия",NULL)')
    c.execute('INSERT INTO places VALUES(70,"Бонн","city","Германия",NULL)')
    c.execute('INSERT INTO places VALUES(71,"Кёльн","city","Германия",NULL)')
    c.execute('INSERT INTO places VALUES(72,"Вюрцбург","city","Германия",NULL)')
    c.execute('INSERT INTO places VALUES(73,"Франкфурт-на-Майне","city","Германия",NULL)')
    c.execute('INSERT INTO places VALUES(74,"Дюссельдорф","city","Германия",NULL)')
    c.execute('INSERT INTO places VALUES(75,"Мюнхен","city","Германия",NULL)')
    c.execute('INSERT INTO places VALUES(76,"Тверь","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(77,"Киев","city","Украина",NULL)')
    c.execute('INSERT INTO places VALUES(78,"Москва","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(79,"Ростов Великий","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(80,"Коломна","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(81,"Дубна","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(82,"Барселона","city","Испания",NULL)')
    c.execute('INSERT INTO places VALUES(83,"Арль","city","Франция",NULL)')
    c.execute('INSERT INTO places VALUES(84,"Марсель","city","Франция",NULL)')
    c.execute('INSERT INTO places VALUES(85,"Свияжск","town","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(86,"Зёльден","city","Австрия",NULL)')
    c.execute('INSERT INTO places VALUES(87,"Минск","city","Белоруссия",NULL)')
    c.execute('INSERT INTO places VALUES(88,"Петрозаводск","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(89,"Вологда","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(90,"Чешски-Крумлов","city","Чехия",NULL)')
    c.execute('INSERT INTO places VALUES(91,"Прага","city","Чехия",NULL)')
    c.execute('INSERT INTO places VALUES(92,"Одесса","city","Украина",NULL)')
    c.execute('INSERT INTO places VALUES(93,"Рига","city","Латвия",NULL)')
    c.execute('INSERT INTO places VALUES(94,"Берлин","city","Германия",NULL)')
    c.execute('INSERT INTO places VALUES(95,"Саарбукен","city","Германия",NULL)')
    c.execute('INSERT INTO places VALUES(96,"Париж","city","Франция",NULL)')
    c.execute('INSERT INTO places VALUES(97,"Милан","city","Италия",NULL)')
    c.execute('INSERT INTO places VALUES(98,"Таллин","city","Эстония",NULL)')
    c.execute('INSERT INTO places VALUES(99,"Хельсинки","city","Финляндия",NULL)')
    c.execute('INSERT INTO places VALUES(100,"Турку","city","Финляндия",NULL)')
    c.execute('INSERT INTO places VALUES(101,"Тампере","city","Финляндия",NULL)')
    c.execute('INSERT INTO places VALUES(102,"Саратов","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(103,"Иваново","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(104,"Лазаревское","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(105,"Гусь Хрустальный","city","Россия",NULL)')
    c.execute('INSERT INTO places VALUES(106,"Мещовск","city","Россия",NULL)')