# coding=utf-8
import sqlite3

with sqlite3.connect("sample.db") as connection:
    c = connection.cursor()
    c.execute('DROP TABLE posts')
    #c.execute('DROP TABLE visits(visit_id INTEGER, place_id INTEGER, visit_date TEXT)')
    #c.execute('CREATE TABLE places(place_id INTEGER, place_name TEXT, place_type TEXT, place_country TEXT, place_region TEXT)')
    c.execute('CREATE TABLE posts(post_id INTEGER, post_title TEXT, post_body TEXT, post_timestamp DATE, post_tags TEXT)')
    #c.execute('CREATE TABLE visits(visit_id INTEGER, place_id INTEGER, visit_date TEXT)')
    #c.execute('INSERT INTO visits VALUES(1001,1,"апрель 2016")')
    #c.execute('INSERT INTO visits VALUES(1002,2,"сентябрь 2016")')
    c.execute('INSERT INTO books VALUES(20001,0,"The everything store — about Amazon","Brad Stown","","")')
    c.execute('INSERT INTO books VALUES(20002,0,"Кто сказал, что слоны не умеют танцевать? Возрождение корпорации IBM: взгляд изнутри","Луис Герстнер","","")')
    c.execute('INSERT INTO books VALUES(20003,0,"Инструменты McKinsey","Итан Расиел","","")')
    c.execute('INSERT INTO books VALUES(20004,0,"Маркетинговые войны","Джек Траут, Эл Райс","","")')
    c.execute('INSERT INTO books VALUES(20005,0,"45 татуировок менеджера","Максим Батырев","","")')
    c.execute('INSERT INTO books VALUES(20006,0,"Агрессия","Конрад Лоренц","","")')
    c.execute('INSERT INTO books VALUES(20007,0,"Взлом Маркетинга","Фил Барден","","")')
    c.execute('INSERT INTO books VALUES(20008,0,"Переломный момент","Малкольм Гладуэлл","","")')
    c.execute('INSERT INTO books VALUES(20009,0,"Getting Real by 37signals","","для тех кто не в IT","")')
    c.execute('INSERT INTO books VALUES(20010,0,"«Ководство» ","Артемий Лебедев","","")')
    c.execute('INSERT INTO books VALUES(20011,0,"Огилви о рекламе","Дэвид Огилви","","")')
    c.execute('INSERT INTO books VALUES(20012,0,"«Scrum. Революционный метод управления проектами»","Джефф Сазерленд ","ноябрь-декабрь 2016","")')
    c.execute('INSERT INTO books VALUES(20013,1,"Сам себе MBA","Джош Кауфман","","")')
    c.execute('INSERT INTO books VALUES(20014,1,"Теория игр. Искусство стратегического мышления в бизнесе и жизни","Авинаш Диксит","","")')
    c.execute('INSERT INTO books VALUES(20015,1,"Дизай: форма и хаос","Пол Рэнд","если только ты не ярый дизайнер","")')
    c.execute('INSERT INTO books VALUES(20016,1,"Как пасти котов","Дж. Ханк Рейнвотер","жуткое занудство далекое от жизни","basic management")')
    c.execute('INSERT INTO books VALUES(20017,2,"Краткая история почти всего","","рекомендую","")')
    c.execute('INSERT INTO books VALUES(20018,2,"Структура научных революций","","рекомендую","")')
    c.execute('INSERT INTO books VALUES(20019,2,"После структуры научных революций","","","")')
    c.execute('INSERT INTO books VALUES(20020,2,"Стратегический менеджмент","","","")')
    c.execute('INSERT INTO books VALUES(20021,2,"Научите себя думать","","","")')
    c.execute('INSERT INTO books VALUES(20022,2,"Сила воли, как развить и укрепить"," ","","")')
    c.execute('INSERT INTO books VALUES(20023,2,"Друкер на каждый день","","","")')
    c.execute('INSERT INTO books VALUES(20024,2,"Как плавать каждый день среди акул и не быть съеденным заживо","","","")')
    c.execute('INSERT INTO books VALUES(20025,2,"Искусство подбора персонала","","","")')
    c.execute('INSERT INTO books VALUES(20026,2,"Naked statistic","","","")')
    c.execute('INSERT INTO books VALUES(20027,2,"Contagious: why things catch on ","Jonah Berger","","")')
    c.execute('INSERT INTO books VALUES(20028,2,"Gamification and game mechanics made simple","Patrick Chapman","","")')
    c.execute('INSERT INTO books VALUES(20029,2,"Managing risk and information security","","","")')
    c.execute('INSERT INTO books VALUES(20030,2,"Social networks and popular understanding of science and health","","","")')
    c.execute('INSERT INTO books VALUES(20031,2,"Стратегия голубого океана","","","")')
    c.execute('INSERT INTO books VALUES(20032,2,"Слон на танцполе","","","")')
    c.execute('INSERT INTO books VALUES(20033,2,"Искусство войны","","","")')
    c.execute('INSERT INTO books VALUES(20034,2,"Good to great by Jim Collins","","","")')
    c.execute('INSERT INTO books VALUES(20035,2,"Черный лебедь,  под знаком непредсказуемости","","","")')
    c.execute('INSERT INTO books VALUES(20036,2,"Дизай: форма и хаос","","","")')
    c.execute('INSERT INTO books VALUES(20037,2,"Пинбол эффект","","","")')
    c.execute('INSERT INTO books VALUES(20038,2,"50 идей - психология","","","")')
    c.execute('INSERT INTO books VALUES(20039,2,"Мозг за 30 секунд","","","")')
    c.execute('INSERT INTO books VALUES(20040,2,"Архитектура за 30 секунд","","","")')
    c.execute('INSERT INTO books VALUES(20041,2,"Психология за 30 секунд","","","")')
    c.execute('INSERT INTO books VALUES(20042,2,"Говори на языке диаграмм","","","")')
    c.execute('INSERT INTO books VALUES(20043,2,"Искусство управления проектами","Скотт Беркун","","basic management")')
    c.execute('INSERT INTO books VALUES(20044,2,"Мифический человеко-месяц","Фредерик П.Брукс.","","basic management")')
    c.execute('INSERT INTO books VALUES(20045,2,"Deadline. Роман об управлении проектами","Том Демарко","","basic management")')
    c.execute('INSERT INTO books VALUES(20046,2,"Общаться с ребенком. Как?","Ю. Гиппенрейтер","","advanced management")')
    c.execute('INSERT INTO books VALUES(20047,2,"Парадигмы Мышления ","Джоэл Баркер","","advanced management")')
    c.execute('INSERT INTO books VALUES(20048,2,"Человеческий фактор. Успешные проекты и команды ","Том Демарко","","advanced management")')
    c.execute('INSERT INTO books VALUES(20049,2,"Management 3.0: Leading Agile Developers,  Developing Agile Leaders ","Jurgen Appello","","advanced management")')
    c.execute('INSERT INTO books VALUES(20050,2,"Продавая незримое. Руководство по современному маркетингу услуг ","Гарри Беквит","","advanced management")')
    c.execute('INSERT INTO books VALUES(20051,2,"Дифференцируйся или умирай!","Траут","","advanced management")')
    c.execute('INSERT INTO books VALUES(20052,2,"Бизнес со скоростью мысли","Билл Гейтс","","advanced management")')
    c.execute('INSERT INTO books VALUES(20053,2,"Интерфейс. Новые направления в проектировании компьютерных систем","Джеф Раскин","","design_for_managers")')
    c.execute('INSERT INTO books VALUES(20054,2,"Tog to interface","Bruce Tognazzini","","design_for_managers")')
    c.execute('INSERT INTO books VALUES(20055,2,"Design web-usability","Jacob Nielsen","","design_for_managers")')
    c.execute('INSERT INTO books VALUES(20057,2,"Веб-Дизайн","Дмитрий Кирсанов","","design_for_managers")')
    c.execute('INSERT INTO books VALUES(20058,2,"Grid Systems in Graphic Design/Raster Systeme Fur Die Visuele Gestaltung (German and English Edition)","Josef Muller-Brockmann","","design_for_managers")')
    c.execute('INSERT INTO books VALUES(20059,2,"The Elements of Typographic Style","Robert Bringhurst","","design_for_managers")')
    c.execute('INSERT INTO books VALUES(20060,2,"The Visual Display of Quantitative Information","Edward R. Tufte","","design_for_managers")')
    c.execute('INSERT INTO books VALUES(20061,2,"Envisioning Information","Edward R. Tufte","","design_for_managers")')
    c.execute('INSERT INTO books VALUES(20062,2,"Visual Explanations: Images and Quantities, Evidence and Narrative","Edward R. Tufte","","design_for_managers")')
    c.execute('INSERT INTO books VALUES(20063,2,"Beautiful Evidence","Edward R. Tufte","","design_for_managers")')
    c.execute('INSERT INTO books VALUES(20064,2,"The Design of Everyday Things","Donald  A. Norman","","design_for_managers")')
    c.execute('INSERT INTO books VALUES(20065,2,"Психбольница в руках пациентов","Алан Купер","","design_for_managers")')
    c.execute('INSERT INTO books VALUES(20066,2,"Организационное поведение","Роббинз","","hr")')
    c.execute('INSERT INTO books VALUES(20067,2,"Власть и влияние","Пфеффер","","hr")')
    c.execute('INSERT INTO books VALUES(20068,2,"Выбор сильнейших","Клаудио Фернандес-Арраос","","hr")')
    c.execute('INSERT INTO books VALUES(20069,2,"Война за таланты","","","hr")')
    c.execute('INSERT INTO books VALUES(20070,2,"Копайте колодец до того, как захочется пить","Харви Маккей","","hr")')
    c.execute('INSERT INTO books VALUES(20071,2,"Мои годы в GE ","Джек Уэлч","","autobiography")')
    c.execute('INSERT INTO books VALUES(20072,2,"Победитель","Джек Уэлч","","autobiography")')
    c.execute('INSERT INTO books VALUES(20073,2,"Моя жизнь, мои достижения"," Форд","","autobiography")')
    c.execute('INSERT INTO books VALUES(20074,2,"О чем молчит БигМак","","","autobiography")')
    c.execute('INSERT INTO books VALUES(20075,2,"От Dell без посредников","","","autobiography")')
    c.execute('INSERT INTO books VALUES(20076,2,"Мышление стратега","Омое","","strategy")')
    c.execute('INSERT INTO books VALUES(20077,2,"Стратегия непрямых действий","Лиддел Карт","","strategy")')
    c.execute('INSERT INTO books VALUES(20078,2,"Социальная психология","Майерс","","psychology")')
    c.execute('INSERT INTO books VALUES(20079,2,"Психология влияния","Чалдин","","psychology")')
    c.execute('INSERT INTO books VALUES(20080,2,"Откровения рекламного агента","Дэвид Огилви","","")')
    c.execute('INSERT INTO books VALUES(20081,2,"Пришел, увидел, победил","Стефани Палмер","","")')
    c.execute('INSERT INTO books VALUES(20082,2,"Сначала скажите нет","Джим Кэмп","","")')
    c.execute('INSERT INTO books VALUES(20083,2,"Барбара Минто - Принципы пирамиды Минто","","","")')
    c.execute('INSERT INTO books VALUES(20084,2,"iПрезентация (для выступлений на конференциях)","Кармин Галло","","")')
    c.execute('INSERT INTO books VALUES(20085,2,"Культурный код","Клотер Рапай","","")')
    c.execute('INSERT INTO books VALUES(20086,2," Как не стать заложником","Джордж Колризер","","")')
    c.execute('INSERT INTO books VALUES(20087,2,"Реворк","Джейсон Фрайд, Дэвид Хейнмейер Ханссон","","")')
    c.execute('INSERT INTO books VALUES(20088,2,"Стартап","Гай Кавасаки","","")')
    c.execute('INSERT INTO books VALUES(20089,2,"Озарение","Майкл Гладуэл","","")')
    c.execute('INSERT INTO books VALUES(20090,2,"Как рисовать на салфетках","Ден Роам","","")')